"""empty message

Revision ID: 102b6e9b8ee
Revises: None
Create Date: 2017-04-16 20:53:13.898143

"""

# revision identifiers, used by Alembic.
revision = '102b6e9b8ee'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company', sa.Boolean(), nullable=True))
    op.drop_column('users', 'location')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'company')
    ### end Alembic commands ###
