"""empty message

Revision ID: 18207f14e08
Revises: None
Create Date: 2017-04-15 23:03:16.698911

"""

# revision identifiers, used by Alembic.
revision = '18207f14e08'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('done_job', sa.Boolean(), nullable=True))
    op.drop_column('users', 'location')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'done_job')
    ### end Alembic commands ###
