"""empty message

Revision ID: 18d99ad55c2
Revises: 4824d6d08a4
Create Date: 2017-03-26 16:34:43.021507

"""

# revision identifiers, used by Alembic.
revision = '18d99ad55c2'
down_revision = '4824d6d08a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
