"""empty message

Revision ID: 1b5b94e53f1
Revises: 46728e83500
Create Date: 2017-04-24 15:35:37.699909

"""

# revision identifiers, used by Alembic.
revision = '1b5b94e53f1'
down_revision = '46728e83500'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
