"""empty message

Revision ID: 2907aacb25b
Revises: 2d3ed17aeb3
Create Date: 2017-04-24 05:09:16.774067

"""

# revision identifiers, used by Alembic.
revision = '2907aacb25b'
down_revision = '2d3ed17aeb3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
