"""empty message

Revision ID: 2d3ed17aeb3
Revises: 3c41bbbda87
Create Date: 2017-04-24 05:07:36.215304

"""

# revision identifiers, used by Alembic.
revision = '2d3ed17aeb3'
down_revision = '3c41bbbda87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
