"""empty message

Revision ID: 2d4d23d20a2
Revises: None
Create Date: 2017-04-17 05:51:44.710445

"""

# revision identifiers, used by Alembic.
revision = '2d4d23d20a2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'author_id')
    op.drop_column('users', 'location')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=64), nullable=True))
    op.add_column('applications', sa.Column('author_id', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
