"""empty message

Revision ID: 310a23f1766
Revises: None
Create Date: 2017-04-17 01:14:37.984749

"""

# revision identifiers, used by Alembic.
revision = '310a23f1766'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('industry', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=64), nullable=True))
    op.drop_column('users', 'location')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'website')
    op.drop_column('users', 'industry')
    ### end Alembic commands ###
