"""empty message

Revision ID: 31669d070c6
Revises: 3ac5f27a260
Create Date: 2017-04-24 05:06:41.927687

"""

# revision identifiers, used by Alembic.
revision = '31669d070c6'
down_revision = '3ac5f27a260'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
