"""empty message

Revision ID: 3ac5f27a260
Revises: 431a8d022ba
Create Date: 2017-04-24 05:02:01.644875

"""

# revision identifiers, used by Alembic.
revision = '3ac5f27a260'
down_revision = '431a8d022ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('workers', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'workers')
    ### end Alembic commands ###
