"""empty message

Revision ID: 3c41bbbda87
Revises: 31669d070c6
Create Date: 2017-04-24 05:07:03.160498

"""

# revision identifiers, used by Alembic.
revision = '3c41bbbda87'
down_revision = '31669d070c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
