"""migration


Revision ID: 41fce4a80ce1
Revises: c624c74e9b
Create Date: 2017-04-25 01:44:18.135688

"""

# revision identifiers, used by Alembic.
revision = '41fce4a80ce1'
down_revision = 'c624c74e9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
