"""empty message

Revision ID: 431a8d022ba
Revises: 4ed4311ae64
Create Date: 2017-04-24 03:53:29.486923

"""

# revision identifiers, used by Alembic.
revision = '431a8d022ba'
down_revision = '4ed4311ae64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('approved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'approved')
    ### end Alembic commands ###
