"""empty message

Revision ID: 44cc6380433
Revises: 39e7f3c5d9d
Create Date: 2017-04-23 22:39:50.803333

"""

# revision identifiers, used by Alembic.
revision = '44cc6380433'
down_revision = '39e7f3c5d9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
