"""empty message

Revision ID: 47db917891d
Revises: 51f5ccfba190
Create Date: 2017-03-18 16:03:17.299448

"""

# revision identifiers, used by Alembic.
revision = '47db917891d'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
