"""empty message

Revision ID: 4824d6d08a4
Revises: 47db917891d
Create Date: 2017-03-18 16:01:09.839515

"""

# revision identifiers, used by Alembic.
revision = '4824d6d08a4'
down_revision = '47db917891d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
