"""empty message

Revision ID: 4ed4311ae64
Revises: 44cc6380433
Create Date: 2017-04-23 22:55:02.899342

"""

# revision identifiers, used by Alembic.
revision = '4ed4311ae64'
down_revision = '44cc6380433'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('applicant_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'applicant_count')
    ### end Alembic commands ###
