"""empty message

Revision ID: 5467002bb30
Revises: 5bafd21b29
Create Date: 2017-04-24 15:38:55.829740

"""

# revision identifiers, used by Alembic.
revision = '5467002bb30'
down_revision = '5bafd21b29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
