"""empty message

Revision ID: 5bafd21b29
Revises: 1b5b94e53f1
Create Date: 2017-04-24 15:37:24.880306

"""

# revision identifiers, used by Alembic.
revision = '5bafd21b29'
down_revision = '1b5b94e53f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
