"""empty message

Revision ID: c624c74e9b
Revises: 5467002bb30
Create Date: 2017-04-24 19:29:43.665839

"""

# revision identifiers, used by Alembic.
revision = 'c624c74e9b'
down_revision = '5467002bb30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('job_completed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'job_completed')
    ### end Alembic commands ###
